# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  GLFW_config = debug
  Glad_config = debug
  ImGui_config = debug
  Engine_config = debug
  SandBox_config = debug
  CustomFontRenderer_config = debug

else ifeq ($(config),release)
  GLFW_config = release
  Glad_config = release
  ImGui_config = release
  Engine_config = release
  SandBox_config = release
  CustomFontRenderer_config = release

else ifeq ($(config),dist)
  GLFW_config = dist
  Glad_config = dist
  ImGui_config = dist
  Engine_config = dist
  SandBox_config = dist
  CustomFontRenderer_config = dist

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := GLFW Glad ImGui Engine SandBox CustomFontRenderer

.PHONY: all clean help $(PROJECTS) Dependencies

all: $(PROJECTS)

Dependencies: GLFW Glad ImGui

GLFW:
ifneq (,$(GLFW_config))
	@echo "==== Building GLFW ($(GLFW_config)) ===="
	@${MAKE} --no-print-directory -C Engine/vendor/GLFW -f Makefile config=$(GLFW_config)
endif

Glad:
ifneq (,$(Glad_config))
	@echo "==== Building Glad ($(Glad_config)) ===="
	@${MAKE} --no-print-directory -C Engine/vendor/Glad -f Makefile config=$(Glad_config)
endif

ImGui:
ifneq (,$(ImGui_config))
	@echo "==== Building ImGui ($(ImGui_config)) ===="
	@${MAKE} --no-print-directory -C Engine/vendor/imgui -f Makefile config=$(ImGui_config)
endif

Engine: GLFW Glad ImGui
ifneq (,$(Engine_config))
	@echo "==== Building Engine ($(Engine_config)) ===="
	@${MAKE} --no-print-directory -C Engine -f Makefile config=$(Engine_config)
endif

SandBox: Engine
ifneq (,$(SandBox_config))
	@echo "==== Building SandBox ($(SandBox_config)) ===="
	@${MAKE} --no-print-directory -C SandBox -f Makefile config=$(SandBox_config)
endif

CustomFontRenderer: Engine
ifneq (,$(CustomFontRenderer_config))
	@echo "==== Building CustomFontRenderer ($(CustomFontRenderer_config)) ===="
	@${MAKE} --no-print-directory -C CustomFontRenderer -f Makefile config=$(CustomFontRenderer_config)
endif

clean:
	@${MAKE} --no-print-directory -C Engine/vendor/GLFW -f Makefile clean
	@${MAKE} --no-print-directory -C Engine/vendor/Glad -f Makefile clean
	@${MAKE} --no-print-directory -C Engine/vendor/imgui -f Makefile clean
	@${MAKE} --no-print-directory -C Engine -f Makefile clean
	@${MAKE} --no-print-directory -C SandBox -f Makefile clean
	@${MAKE} --no-print-directory -C CustomFontRenderer -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo "  dist"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   GLFW"
	@echo "   Glad"
	@echo "   ImGui"
	@echo "   Engine"
	@echo "   SandBox"
	@echo "   CustomFontRenderer"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"